[package]
name = "rustic"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.34.0", features = ["bundled", "blob"] }
serde = { version =  "1.0.219", features = ["derive"] }
serde_cbor = "0.11.2"
blake3 = { version = "1.8.1", features = ["serde"] }
zstd = "0.13.3"
uuid = { version = "1.16.0", features = ["v4", "serde"] }
getrandom = "0.3.2"
clap = { version = "4.5.35", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
